# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

#CONFIG_SENSOR=y
#CONFIG_BLINK=y
CONFIG_ADC=y
CONFIG_ADC_ADS1220=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_PRINTK=y
